# Generated by Django 4.2.6 on 2023-12-29 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dependencias', '0002_provincia'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='provincia',
            unique_together={('codigo', 'nombre')},
        ),
    ]
