# Generated by Django 4.2.6 on 2024-01-09 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0002_tipo_vehiculo_tipo_mantenimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombres_apellidos', models.CharField(max_length=20)),
                ('f_nac', models.DateField()),
                ('t_sangre', models.CharField(max_length=20)),
                ('ciudad_nacimiento', models.CharField(max_length=20)),
                ('celular', models.CharField(max_length=10)),
                ('rango', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.rango')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Personal Policial',
            },
        ),
    ]
