# Generated by Django 4.2.6 on 2024-01-16 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dependencias', '0004_canton_circuito_distrito_canton_distrito_canton_uc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
                ('detalles', models.CharField(max_length=200)),
                ('contacto', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('circuito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dependencias.circuito')),
                ('subcircuito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dependencias.subcircuito')),
            ],
            options={
                'verbose_name_plural': 'Reclamos',
            },
        ),
    ]
