# Generated by Django 4.2.6 on 2024-01-06 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogos', '0002_tipo_vehiculo_tipo_mantenimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlotaVehicular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('placa', models.CharField(help_text='Placa de Vehículo', max_length=10, unique=True)),
                ('chasis', models.CharField(help_text='Chasis de Vehiculo', max_length=30, unique=True)),
                ('marca', models.CharField(help_text='Marca de Vehículo', max_length=20)),
                ('modelo', models.CharField(help_text='Modelo de Vehículo', max_length=30)),
                ('motor', models.CharField(help_text='Motor de Vehículo', max_length=20)),
                ('kilometraje', models.CharField(help_text='Motor de Vehículo', max_length=20)),
                ('cilindraje', models.CharField(help_text='Motor de Vehículo', max_length=20)),
                ('capacidad_carga', models.CharField(help_text='Motor de Vehículo', max_length=20)),
                ('capacidad_pasajeros', models.CharField(help_text='Motor de Vehículo', max_length=20)),
                ('flotavehicular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.tipo_vehiculo')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'FlotasVehiculares',
                'unique_together': {('placa', 'chasis')},
            },
        ),
    ]
