# Generated by Django 4.2.6 on 2024-01-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flotavehicular', '0002_rename_flotavehicular_flotavehicular_tipovehiculo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flotavehicular',
            name='capacidad_carga',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='flotavehicular',
            name='capacidad_pasajeros',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='flotavehicular',
            name='chasis',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='flotavehicular',
            name='cilindraje',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='flotavehicular',
            name='kilometraje',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='flotavehicular',
            name='marca',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='flotavehicular',
            name='modelo',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='flotavehicular',
            name='motor',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='flotavehicular',
            name='placa',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
